export const LOAD_DRIVERS = "LOAD_DRIVERS";
export const LOAD_DRIVER_STANDINGS = "LOAD_DRIVER_STANDINGS";

export const LOAD_CONSTRUCTORS = "LOAD_CONSTRUCTORS";
export const LOAD_CONSTRUCTOR_STANDINGS = "LOAD_CONSTRUCTOR_STANDINGS";
